#BASE_DIR='/mnt/data1/adoni/jd_data/'
BASE_DIR='/Users/sunxiaofei/workspace/TMPDATA/jd_data/'
RAW_DATA_DIR=BASE_DIR+'raw_data/'
VECTORS_DIR=BASE_DIR+'vectors/'
MATRIXES_DIR=BASE_DIR+'matrixes/'
MALLET_DIR=BASE_DIR+'mallet/'
